import type { Ticket, CalendarEvent, Summary } from '../components/pm/types';

// ─────────────────────────────────────────────────────────────────────────────
// DEMO TICKETS — realistic dental IT MSP support queue
// 15 tickets across 8 fake practices, mix of open/pending/closed
// ─────────────────────────────────────────────────────────────────────────────
export const DEMO_TICKETS: Ticket[] = [
  // ── URGENT / HIGH PRIORITY ──────────────────────────────────────────────
  {
    id: 1001,
    ticket_key: 'TKT-2891',
    title: 'Eaglesoft not launching after Windows update',
    title_clean: 'Eaglesoft not launching after Windows update',
    status: 'open',
    priority: 'high',
    client_key: 'sunrise-family',
    client_display_name: 'Sunrise Family Dentistry',
    sender_name: 'Dr. Amanda Chen',
    sender_email: 'dr.chen@sunrisefamilydental.com',
    readiness_signal: 'HIGH',
    readiness_score: 88,
    trust_signal: 'RISING',
    trust_score: 82,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'TIME',
    decision_signal: 'RESOLVE',
    decision_label: 'RESOLVE/VERIFY',
    decision_detail: 'Patterson SQL service not starting. KB5034441 rollback required.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-27',
    needs_response: 1,
    created_at: '2026-02-27T07:12:00',
    last_updated: '2026-02-27T07:45:00',
    notes_count: 3,
  },
  {
    id: 1002,
    ticket_key: 'TKT-2887',
    title: 'RANSOMWARE WARNING POPUP — please advise URGENT',
    title_clean: 'Ransomware warning popup — please advise URGENT',
    status: 'closed',
    priority: 'critical',
    client_key: 'pinnacle-dental',
    client_display_name: 'Pinnacle Dental Group',
    sender_name: 'Office Manager - Lisa Park',
    sender_email: 'lisa@pinnacledental.com',
    readiness_signal: 'HIGH',
    readiness_score: 91,
    trust_signal: 'RISING',
    trust_score: 87,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'SECURITY',
    decision_signal: 'RESOLVE',
    decision_label: 'RESOLVE/VERIFY',
    decision_detail: 'Isolated to one workstation. False positive from expired Malwarebytes license. Renewed + full scan completed clean.',
    lifecycle_status: 'resolved',
    appointment_at: null,
    due_date: '2026-02-25',
    needs_response: 0,
    created_at: '2026-02-25T14:22:00',
    last_updated: '2026-02-25T16:55:00',
    notes_count: 7,
  },
  {
    id: 1003,
    ticket_key: 'TKT-2893',
    title: 'Eaglesoft slow since Monday — whole office affected',
    title_clean: 'Eaglesoft slow since Monday — whole office affected',
    status: 'open',
    priority: 'high',
    client_key: 'heritage-smiles',
    client_display_name: 'Heritage Smiles Dental',
    sender_name: 'James Thornton',
    sender_email: 'dr.thornton@heritagesmiles.com',
    readiness_signal: 'HIGH',
    readiness_score: 85,
    trust_signal: 'DECLINING',
    trust_score: 54,
    expectation_signal: 'MISALIGNED',
    constraint_signal: 'TIME',
    decision_signal: 'RESOLVE',
    decision_label: 'RESOLVE/VERIFY',
    decision_detail: 'Linked to KB5034441 — Patterson SQL service degraded. 4 ops chairs impacted.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-27',
    needs_response: 1,
    created_at: '2026-02-27T08:05:00',
    last_updated: '2026-02-27T09:10:00',
    notes_count: 4,
  },
  {
    id: 1004,
    ticket_key: 'TKT-2889',
    title: 'DEXIS sensor not recognized after driver update',
    title_clean: 'DEXIS sensor not recognized after driver update',
    status: 'open',
    priority: 'high',
    client_key: 'lakefront-oral',
    client_display_name: 'Lakefront Oral Surgery',
    sender_name: 'Dr. Patricia Novak',
    sender_email: 'p.novak@lakefrontoralsurgery.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 67,
    trust_signal: 'NEUTRAL',
    trust_score: 71,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'TECHNICAL',
    decision_signal: 'ASSESS',
    decision_label: 'ASSESS/RECOMMEND',
    decision_detail: 'DEXIS Platinum sensor unresponsive in op 2. Driver v4.1.2 may conflict with Win 11 22H2.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-27',
    needs_response: 1,
    created_at: '2026-02-26T16:44:00',
    last_updated: '2026-02-27T08:30:00',
    notes_count: 2,
  },
  // ── MEDIUM PRIORITY ──────────────────────────────────────────────────────
  {
    id: 1005,
    ticket_key: 'TKT-2885',
    title: 'Backup job failed — drive full on server',
    title_clean: 'Backup job failed — drive full on server',
    status: 'open',
    priority: 'medium',
    client_key: 'westside-pediatric',
    client_display_name: 'Westside Pediatric Dental',
    sender_name: 'Dr. Marcus Webb',
    sender_email: 'm.webb@westsidepediatric.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 61,
    trust_signal: 'NEUTRAL',
    trust_score: 68,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'RESOURCE',
    decision_signal: 'PROCEED',
    decision_label: 'PROCEED/HALT',
    decision_detail: 'Veeam backup failed 3 nights in a row. D:\ drive at 97% capacity. Imaging archive cleanup needed.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-28',
    needs_response: 1,
    created_at: '2026-02-26T08:15:00',
    last_updated: '2026-02-27T06:00:00',
    notes_count: 3,
  },
  {
    id: 1006,
    ticket_key: 'TKT-2890',
    title: 'Mango Voice calls dropping intermittently',
    title_clean: 'Mango Voice calls dropping intermittently',
    status: 'open',
    priority: 'medium',
    client_key: 'clearwater-ortho',
    client_display_name: 'Clearwater Orthodontics',
    sender_name: 'Sofia Reyes',
    sender_email: 'dr.reyes@clearwaterortho.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 58,
    trust_signal: 'NEUTRAL',
    trust_score: 72,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'TECHNICAL',
    decision_signal: 'ASSESS',
    decision_label: 'ASSESS/RECOMMEND',
    decision_detail: 'VoIP drops every 20-40 min. Likely QoS config on Meraki. ISP bandwidth test normal.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-28',
    needs_response: 0,
    created_at: '2026-02-26T11:30:00',
    last_updated: '2026-02-26T14:20:00',
    notes_count: 2,
  },
  {
    id: 1007,
    ticket_key: 'TKT-2883',
    title: 'New hire workstation setup needed by Friday',
    title_clean: 'New hire workstation setup needed by Friday',
    status: 'pending',
    priority: 'medium',
    client_key: 'summit-implant',
    client_display_name: 'Summit Implant Center',
    sender_name: 'David Okafor',
    sender_email: 'dr.okafor@summitimplant.com',
    readiness_signal: 'HIGH',
    readiness_score: 79,
    trust_signal: 'RISING',
    trust_score: 84,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'TIME',
    decision_signal: 'PROCEED',
    decision_label: 'PROCEED/HALT',
    decision_detail: 'New clinical coordinator starts Friday. Needs Eaglesoft access, HIPAA training workstation, email setup.',
    lifecycle_status: 'scheduled',
    appointment_at: '2026-02-28T09:00:00',
    due_date: '2026-02-28',
    needs_response: 0,
    created_at: '2026-02-24T10:00:00',
    last_updated: '2026-02-25T09:30:00',
    notes_count: 5,
  },
  {
    id: 1008,
    ticket_key: 'TKT-2886',
    title: 'CEREC design software license expired',
    title_clean: 'CEREC design software license expired',
    status: 'pending',
    priority: 'medium',
    client_key: 'pinnacle-dental',
    client_display_name: 'Pinnacle Dental Group',
    sender_name: 'Robert Hayes',
    sender_email: 'dr.hayes@pinnacledental.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 63,
    trust_signal: 'RISING',
    trust_score: 80,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'LICENSING',
    decision_signal: 'PROCEED',
    decision_label: 'PROCEED/HALT',
    decision_detail: 'Dentsply Sirona CEREC Ortho SW expired 02/24. Renewal invoice sent to Dr. Hayes. Awaiting PO.',
    lifecycle_status: 'waiting_client',
    appointment_at: null,
    due_date: '2026-03-01',
    needs_response: 0,
    created_at: '2026-02-25T09:00:00',
    last_updated: '2026-02-25T15:00:00',
    notes_count: 4,
  },
  {
    id: 1009,
    ticket_key: 'TKT-2892',
    title: 'Printer offline in operatory 3',
    title_clean: 'Printer offline in operatory 3',
    status: 'open',
    priority: 'low',
    client_key: 'heritage-smiles',
    client_display_name: 'Heritage Smiles Dental',
    sender_name: 'James Thornton',
    sender_email: 'dr.thornton@heritagesmiles.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 55,
    trust_signal: 'DECLINING',
    trust_score: 54,
    expectation_signal: 'ALIGNED',
    constraint_signal: null,
    decision_signal: 'VERIFY',
    decision_label: 'VERIFY/SIGN-OFF',
    decision_detail: 'HP LaserJet Pro M404n offline. Likely IP conflict after router change last week.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-27',
    needs_response: 0,
    created_at: '2026-02-27T09:30:00',
    last_updated: '2026-02-27T09:30:00',
    notes_count: 1,
  },
  {
    id: 1010,
    ticket_key: 'TKT-2894',
    title: 'Eaglesoft error on imaging workstation after update',
    title_clean: 'Eaglesoft error on imaging workstation after update',
    status: 'open',
    priority: 'high',
    client_key: 'pinnacle-dental',
    client_display_name: 'Pinnacle Dental Group',
    sender_name: 'Lisa Park',
    sender_email: 'lisa@pinnacledental.com',
    readiness_signal: 'HIGH',
    readiness_score: 86,
    trust_signal: 'RISING',
    trust_score: 87,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'TIME',
    decision_signal: 'RESOLVE',
    decision_label: 'RESOLVE/VERIFY',
    decision_detail: 'Imaging station WS-04 throwing SQL connection error. Same KB5034441 root cause. Fix in progress.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-27',
    needs_response: 1,
    created_at: '2026-02-27T08:55:00',
    last_updated: '2026-02-27T09:15:00',
    notes_count: 2,
  },
  {
    id: 1011,
    ticket_key: 'TKT-2880',
    title: 'Cannot access patient records remotely — VPN broken',
    title_clean: 'Cannot access patient records remotely — VPN broken',
    status: 'closed',
    priority: 'high',
    client_key: 'summit-implant',
    client_display_name: 'Summit Implant Center',
    sender_name: 'David Okafor',
    sender_email: 'dr.okafor@summitimplant.com',
    readiness_signal: 'HIGH',
    readiness_score: 81,
    trust_signal: 'RISING',
    trust_score: 84,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'ACCESS',
    decision_signal: 'RESOLVE',
    decision_label: 'RESOLVE/VERIFY',
    decision_detail: 'Fortinet SSL-VPN cert expired 02/21. Renewed + tested. Remote access restored for Dr. Okafor.',
    lifecycle_status: 'resolved',
    appointment_at: null,
    due_date: '2026-02-22',
    needs_response: 0,
    created_at: '2026-02-21T18:30:00',
    last_updated: '2026-02-22T11:45:00',
    notes_count: 6,
  },
  {
    id: 1012,
    ticket_key: 'TKT-2877',
    title: 'DEXIS imaging system freezing during x-ray capture',
    title_clean: 'DEXIS imaging system freezing during x-ray capture',
    status: 'closed',
    priority: 'high',
    client_key: 'coastal-kids',
    client_display_name: 'Coastal Kids Dentistry',
    sender_name: 'Yuki Tanaka',
    sender_email: 'dr.tanaka@coastalkids.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 64,
    trust_signal: 'NEUTRAL',
    trust_score: 69,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'TECHNICAL',
    decision_signal: 'RESOLVE',
    decision_label: 'RESOLVE/VERIFY',
    decision_detail: 'RAM upgrade resolved freezing issue. Also updated DEXIS drivers to v4.1.1 stable. Monitoring.',
    lifecycle_status: 'resolved',
    appointment_at: null,
    due_date: '2026-02-20',
    needs_response: 0,
    created_at: '2026-02-19T11:00:00',
    last_updated: '2026-02-20T14:30:00',
    notes_count: 8,
  },
  {
    id: 1013,
    ticket_key: 'TKT-2878',
    title: 'Server room overheating — UPS beeping',
    title_clean: 'Server room overheating — UPS beeping',
    status: 'closed',
    priority: 'high',
    client_key: 'lakefront-oral',
    client_display_name: 'Lakefront Oral Surgery',
    sender_name: 'Patricia Novak',
    sender_email: 'p.novak@lakefrontoralsurgery.com',
    readiness_signal: 'HIGH',
    readiness_score: 77,
    trust_signal: 'NEUTRAL',
    trust_score: 71,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'ENVIRONMENT',
    decision_signal: 'PROCEED',
    decision_label: 'PROCEED/HALT',
    decision_detail: 'HVAC unit failed over weekend. Portable AC unit deployed. HVAC repair scheduled 02/26. UPS battery healthy.',
    lifecycle_status: 'resolved',
    appointment_at: null,
    due_date: '2026-02-24',
    needs_response: 0,
    created_at: '2026-02-22T09:00:00',
    last_updated: '2026-02-24T16:00:00',
    notes_count: 9,
  },
  {
    id: 1014,
    ticket_key: 'TKT-2881',
    title: 'Email not syncing on front desk iPad',
    title_clean: 'Email not syncing on front desk iPad',
    status: 'closed',
    priority: 'low',
    client_key: 'clearwater-ortho',
    client_display_name: 'Clearwater Orthodontics',
    sender_name: 'Sofia Reyes',
    sender_email: 'dr.reyes@clearwaterortho.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 55,
    trust_signal: 'NEUTRAL',
    trust_score: 72,
    expectation_signal: 'ALIGNED',
    constraint_signal: null,
    decision_signal: 'VERIFY',
    decision_label: 'VERIFY/SIGN-OFF',
    decision_detail: 'M365 MDM profile expired on iPad. Re-enrolled via Intune. Email syncing normally.',
    lifecycle_status: 'resolved',
    appointment_at: null,
    due_date: '2026-02-24',
    needs_response: 0,
    created_at: '2026-02-23T08:00:00',
    last_updated: '2026-02-23T10:30:00',
    notes_count: 3,
  },
  {
    id: 1015,
    ticket_key: 'TKT-2884',
    title: 'Veeam backup job failing — cannot connect to repository',
    title_clean: 'Veeam backup job failing — cannot connect to repository',
    status: 'pending',
    priority: 'medium',
    client_key: 'westside-pediatric',
    client_display_name: 'Westside Pediatric Dental',
    sender_name: 'Marcus Webb',
    sender_email: 'm.webb@westsidepediatric.com',
    readiness_signal: 'MEDIUM',
    readiness_score: 58,
    trust_signal: 'NEUTRAL',
    trust_score: 65,
    expectation_signal: 'ALIGNED',
    constraint_signal: 'RESOURCE',
    decision_signal: 'PROCEED',
    decision_label: 'PROCEED/HALT',
    decision_detail: 'Veeam B&R v12 — NAS repository credential mismatch after AD password rotation. Credentials updated, job re-testing overnight.',
    lifecycle_status: 'active',
    appointment_at: null,
    due_date: '2026-02-28',
    needs_response: 0,
    created_at: '2026-02-25T19:30:00',
    last_updated: '2026-02-26T22:00:00',
    notes_count: 4,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// DEMO CALENDAR EVENTS
// ─────────────────────────────────────────────────────────────────────────────
export const DEMO_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 501,
    ticket_id: 1007,
    ticket_key: 'TKT-2883',
    title: 'New hire workstation setup — Summit Implant',
    starts_at_raw: 'Fri 2/28/2026 9:00AM',
    starts_at_iso_utc: '2026-02-28T09:00:00',
    assigned_to: 'Tyler M.',
    assigned_by: 'Dispatch',
    status: 'confirmed',
    client_name: 'Summit Implant Center',
    ticket_title: 'New hire workstation setup needed by Friday',
    decision_label: 'PROCEED/HALT',
  },
  {
    id: 502,
    ticket_id: 1006,
    ticket_key: 'TKT-2890',
    title: 'VoIP QoS review — Clearwater Ortho',
    starts_at_raw: 'Mon 3/2/2026 10:00AM',
    starts_at_iso_utc: '2026-03-02T10:00:00',
    assigned_to: 'Tyler M.',
    assigned_by: 'Dispatch',
    status: 'confirmed',
    client_name: 'Clearwater Orthodontics',
    ticket_title: 'Mango Voice calls dropping intermittently',
    decision_label: 'ASSESS/RECOMMEND',
  },
  {
    id: 503,
    ticket_id: null,
    ticket_key: null,
    title: 'Quarterly Business Review — Sunrise Family',
    starts_at_raw: 'Wed 3/4/2026 2:00PM',
    starts_at_iso_utc: '2026-03-04T14:00:00',
    assigned_to: null,
    assigned_by: null,
    status: 'tentative',
    client_name: 'Sunrise Family Dentistry',
    ticket_title: null,
    decision_label: null,
  },
  {
    id: 504,
    ticket_id: 1005,
    ticket_key: 'TKT-2885',
    title: 'Storage expansion consult — Westside Pediatric',
    starts_at_raw: 'Thu 3/5/2026 11:00AM',
    starts_at_iso_utc: '2026-03-05T11:00:00',
    assigned_to: 'Chris R.',
    assigned_by: 'Dispatch',
    status: 'confirmed',
    client_name: 'Westside Pediatric Dental',
    ticket_title: 'Backup job failed — drive full on server',
    decision_label: 'PROCEED/HALT',
  },
  {
    id: 505,
    ticket_id: null,
    ticket_key: null,
    title: 'Annual security audit — Heritage Smiles',
    starts_at_raw: 'Mon 3/9/2026 9:00AM',
    starts_at_iso_utc: '2026-03-09T09:00:00',
    assigned_to: 'Tyler M.',
    assigned_by: 'Account',
    status: 'confirmed',
    client_name: 'Heritage Smiles Dental',
    ticket_title: null,
    decision_label: null,
  },
  {
    id: 506,
    ticket_id: null,
    ticket_key: null,
    title: 'Eaglesoft version upgrade planning — Pinnacle Dental',
    starts_at_raw: 'Tue 3/10/2026 3:00PM',
    starts_at_iso_utc: '2026-03-10T15:00:00',
    assigned_to: null,
    assigned_by: null,
    status: 'tentative',
    client_name: 'Pinnacle Dental Group',
    ticket_title: null,
    decision_label: null,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// DEMO SUMMARY — matches Summary type exactly
// ─────────────────────────────────────────────────────────────────────────────
export const DEMO_SUMMARY: Summary = {
  total_open: 7,
  declining_trust_count: 1,
  today_count: 4,
  signals: {
    'RESOLVE/VERIFY': 4,
    'PROCEED/HALT': 3,
    'ASSESS/RECOMMEND': 2,
    'VERIFY/SIGN-OFF': 1,
  },
  readiness: { high: 5, medium: 4, low: 0 },
  last_updated: new Date().toISOString(),
};

// ─────────────────────────────────────────────────────────────────────────────
// DEMO OUTBREAKS — the showstopper demo feature
// ─────────────────────────────────────────────────────────────────────────────
export const DEMO_OUTBREAKS = [
  {
    id: 'evt-demo-001',
    tool_id: 'eaglesoft',
    tool_name: 'Eaglesoft',
    status: 'active',
    classification: 'update_related',
    affected_clients: [
      'Sunrise Family Dentistry',
      'Heritage Smiles Dental',
      'Pinnacle Dental Group',
    ],
    at_risk_clients: [
      'Westside Pediatric Dental',
      'Coastal Kids Dentistry',
    ],
    first_seen: '2026-02-27T07:45:00',
    last_seen: '2026-02-27T09:15:00',
    ticket_count: 6,
    root_cause:
      'Windows Update KB5034441 (released 2026-02-25) conflicts with Patterson SQL Server 2019 service startup. ' +
      'Affects all Eaglesoft 21.x installations on Windows 11 22H2.',
    recommended_action:
      'Restart Patterson SQL Service via services.msc. If persistent, rollback KB5034441 via Windows Update history. ' +
      'Proactively check Westside Pediatric and Coastal Kids — both on same OS/Eaglesoft version.',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// DEMO TOOL RISK SCORES — matches ToolRow shape for IntelPanel
// ─────────────────────────────────────────────────────────────────────────────
export const DEMO_TOOL_SCORES = [
  {
    id: 'eaglesoft',
    name: 'Eaglesoft',
    vendor: 'Patterson Dental',
    category: 'Practice Mgmt',
    risk_score: 78,
    level: 'HIGH',
    active_tickets: 6,
    clients_affected: 3,
    clients_total: 6,
  },
  {
    id: 'veeam',
    name: 'Veeam Backup',
    vendor: 'Veeam Software',
    category: 'Backup & DR',
    risk_score: 44,
    level: 'MEDIUM',
    active_tickets: 2,
    clients_affected: 2,
    clients_total: 8,
  },
  {
    id: 'dexis',
    name: 'DEXIS Imaging',
    vendor: 'Dentsply Sirona',
    category: 'Dental Imaging',
    risk_score: 31,
    level: 'MEDIUM',
    active_tickets: 2,
    clients_affected: 2,
    clients_total: 4,
  },
  {
    id: 'mango-voice',
    name: 'Mango Voice',
    vendor: 'Mango Voice',
    category: 'VoIP',
    risk_score: 18,
    level: 'LOW',
    active_tickets: 1,
    clients_affected: 1,
    clients_total: 3,
  },
  {
    id: 'windows-server',
    name: 'Windows Server',
    vendor: 'Microsoft',
    category: 'Infrastructure',
    risk_score: 22,
    level: 'LOW',
    active_tickets: 1,
    clients_affected: 1,
    clients_total: 8,
  },
  {
    id: 'microsoft-365',
    name: 'Microsoft 365',
    vendor: 'Microsoft',
    category: 'Productivity',
    risk_score: 12,
    level: 'LOW',
    active_tickets: 1,
    clients_affected: 1,
    clients_total: 8,
  },
  {
    id: 'cerec',
    name: 'CEREC Ortho SW',
    vendor: 'Dentsply Sirona',
    category: 'CAD/CAM',
    risk_score: 35,
    level: 'MEDIUM',
    active_tickets: 1,
    clients_affected: 1,
    clients_total: 2,
  },
  {
    id: 'fortinet-vpn',
    name: 'Fortinet FortiGate',
    vendor: 'Fortinet',
    category: 'Network Security',
    risk_score: 8,
    level: 'LOW',
    active_tickets: 0,
    clients_affected: 0,
    clients_total: 5,
  },
  {
    id: 'malwarebytes',
    name: 'Malwarebytes EDR',
    vendor: 'Malwarebytes',
    category: 'Endpoint Security',
    risk_score: 15,
    level: 'LOW',
    active_tickets: 1,
    clients_affected: 1,
    clients_total: 8,
  },
  {
    id: 'intune',
    name: 'Microsoft Intune',
    vendor: 'Microsoft',
    category: 'MDM',
    risk_score: 9,
    level: 'LOW',
    active_tickets: 0,
    clients_affected: 0,
    clients_total: 6,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// DEMO STATS — for future stats endpoint
// ─────────────────────────────────────────────────────────────────────────────
export const DEMO_STATS = {
  total_tickets: 47,
  open_tickets: 7,
  pending_tickets: 3,
  closed_today: 2,
  clients_total: 8,
  tools_tracked: 21,
  active_outbreaks: 1,
  at_risk_clients: 2,
  avg_resolution_hours: 3.2,
  sla_compliance_pct: 94,
};
